Feature/add security change phone button
LuuTheNguyen/My-CV pull request #11
Opened 2021-09-20 14:35 UTC by LuuTheNguyen

# Add security, change layout contact in mobile view

### Description

-   Add security for page prevent user inspect, copy, cut element.
-  Change contact view.
- Add version

### Preview

|  Change mobile view  | https://imgur.com/bXQuI8r |
| ------------------------ | ------------------------------ |
| Change desktop view | <img src="https://i.imgur.com/eQSZbRI.png" /> |
### Checklist

-   [x] Tested on Desktop
-   [ ] Tested on Tablet
-   [x] Tested on Mobile
-   [x] Tested `Print mode`
-   [ ] Covered with test cases
-   [ ] Added proper label
-   [ ] Performed self-review

2021-09-20 15:50 UTC, tietthinh requested changes
There're a few changes need to be addressed, mostly related to the logic perfomance and naming.
Also there is some place still using semicolon, please remove them as well.

2021-09-20 15:50 UTC, tietthinh commented on containers/Home/Contact/ultis.ts
> +export const handlePhoneNumber = (phoneNumber: string) => {
This should rename to `decodePhoneNumber`. `handle` prefix only for event handling functions

2021-09-20 15:50 UTC, tietthinh commented on containers/Home/Contact/ultis.ts
> +const handleReverseChunkArry = (array: string[]) => {
Also here: `reverseChunks`

2021-09-20 15:50 UTC, tietthinh commented on pages/_document.tsx
> +                    <p style={{display: 'none'}}>Version: {process.env.VERSION}</p>
This should be moved to a separated Component

2021-09-20 15:50 UTC, tietthinh commented on containers/Home/Contact/RenderTypeContact.tsx
> +    switch (type) {
Using `switch case` like this has no meaning, perharp you could use `if else` would be more cleaner like
```
const isAnimatedContent = ['phone', 'skype', 'mail'].indexOf(type) > -1
if(isAnimatedContent) { 
     return ...
}
return ...
```

2021-09-20 15:50 UTC, tietthinh commented on containers/Home/Contact/RenderTypeContact.tsx
> +                        {...linkProps}
Rest Props should be place at first line to avoid overriding,

2021-09-20 15:50 UTC, tietthinh commented on containers/Home/Contact/RenderTypeContact.tsx
> +                        style={{ ...stylesIcon }}
`style={stylesIcon}` ? Why do we need destructor here ?

2021-09-20 15:50 UTC, tietthinh commented on containers/Home/Contact/RenderTypeContact.tsx
> +                            setPropStyleIcon({ rotateZ: 0, loop: false })
We should moveout these two handling functions to a separate functions, it would make clearer render structure's view

2021-09-20 15:50 UTC, tietthinh commented on containers/Home/Contact/RenderTypeContact.tsx
> +    switch (type) {
Also if this is used as a Component please convert it into a proper Component, let React optimize it automatically

2021-09-20 15:50 UTC, tietthinh commented on containers/Home/Contact/interface.ts
> +    linkProps: object;
Don't use `object` use `Record<any,any>`

Ref: https://www.typescriptlang.org/docs/handbook/2/objects.html

2021-09-20 15:50 UTC, tietthinh commented on hooks/useIsMobile.ts
> +        window.addEventListener('resize', handleIsMobile)
I guess this is used mostly in development mode so we should make a condition to avoid in production mode.

2021-09-20 15:50 UTC, tietthinh commented on pages/ultis.ts
> +            if (event.ctrlKey && event.shiftKey && event.keyCode == 'J'.charCodeAt(0)) {
We should optimize performance for these conditions.

2021-09-20 15:50 UTC, tietthinh commented on hooks/useIsMobile.ts
> +        const handleIsMobile = () => {
This could be refactor:

`const handleIsMobile = () => setIsMobile(window.innerWidth <= 1024)`

2021-09-20 15:50 UTC, tietthinh commented on containers/Home/Contact/ultis.ts
> +        chunk = 2
`2` should be moveout as a paramenter, you could set it as default value.

2021-09-21 06:36 UTC, tietthinh requested changes

2021-09-21 06:36 UTC, tietthinh commented on containers/Home/Contact/RenderTypeContact.tsx
> +}
- I don't see where `label` is used.
 - IMO I would change this into 
```
 const renderContent = type === 'phone'  ?  decodePhoneNumber(content) : content
 return  <a {...linkProps}> {renderContent } </a>
```

2021-09-21 06:36 UTC, tietthinh commented on containers/Home/Contact/RenderTypeContact.tsx
> +    } else {
Since `if` it self has `return`  so `else` is unnecessary

2021-09-21 06:36 UTC, tietthinh commented on next.config.js
> +                    '@ultis': path.resolve((__dirname, 'ultis/')),
`utils` ?

2021-09-21 06:36 UTC, tietthinh commented on tsconfig.json
> +            "@ultis/*": ["ultis/*"]
`utils` ?

2021-09-22 03:01 UTC, peace-bi approved these changes
Approve with 1 comment

2021-09-22 03:01 UTC, peace-bi commented on hooks/useIsMobile.ts
> +            return () => window.removeEventListener('resize', handleIsMobile)
[Enhancement]
Put `return` function inside condition is OK. But you should put this `return` outside the condition for avoiding confuse if your code has multiple condition check later.

Example:

```
if (process.env.NODE_ENV === 'development') {
           ...
}
 return () => {
    if (condition here) ...
 }
 ```

reference that post:
https://stackoverflow.com/questions/59890480/can-different-cleanups-be-done-conditionally-in-useeffect#:~:text=Add%20a%20comment-,2%20Answers,-Active

2021-09-22 03:34 UTC, tietthinh approved these changes

2021-09-22 06:30 UTC, peace-bi approved these changes

2021-09-22 06:30 UTC, merged